CREATE DATABASE IF NOT EXISTS loja_db;
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE loja_db;

CREATE TABLE IF NOT EXISTS produtos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  descricao TEXT NOT NULL,
  preco DECIMAL(10, 2) NOT NULL,
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
